<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE define [
	<!ELEMENT define (item+)>
  	<!ELEMENT item (name,desc,init+,use+)>
  	<!ATTLIST item refID CDATA #REQUIRED>
  	<!ATTLIST item scriptLang CDATA "JavaScript">
  	<!ELEMENT name (#PCDATA)>
  	<!ELEMENT desc (#PCDATA)>
  	<!ELEMENT init (#PCDATA)>
  	<!ELEMENT use (#PCDATA)>
]>

<define>
	<item refID="00-HLTH" scriptLang="JavaScript">
		<name>Health Kit</name>
		<desc>A small first-aid kit to heal superficial wounds.%nHeals %healAmt% health.</desc>
		<init>
		setUses(1);
		var healAmt = 10;
		</init>
		<use>	
		if(canUse()) {
			print(&quot;You throw a grenade!&quot;);
			for(let i = 0; i &lt; targets.length; i++) {
				targets[i].damage(dmg);
			}
			used();
		}
		</use>
	</item>
	<item refID="01-PARM" scriptLang="JavaScript">
		<name>Power Armor</name>
		<desc>Powerful armor that increases your defense.</desc>
		<init>
		addStatAura('Strength', 10);
		addStatAura('Intelligence', 3);
		addStatAura('Defense', 5);
		</init>
		<use>
		if(canUse()) {
			print(&quot;!!WARNING!!: Suit does not contain Bubblegum&quot;);
		}
		</use>
	</item>
	<item refID="02-GREN" scriptLang="JavaScript">
		<name>Grenade</name>
		<desc>A simple frag grenade.%nDamage: %dmg%</desc>
		<init>
		setUses(1);
		var dmg = 25;
		</init>
		<use>
		if(canUse) {
			write('You throw a grenade!\nTargets:');
			for(var i = 0; i &lt; targets.length; i++) {
				write(targets[i].getName() + '\n');
			}
			for(var i = 0; i &lt; targets.length; i++) {
				write(targets[i].getName() + ' takes ' + dmg + ' damage!\n');
				targets[i].damage(dmg);
			}
			used();
		}
		</use>
	</item>
	<item refID="03-GRCT" scriptLang="JavaScript">
		<name>Grenade Crate</name>
		<desc>A crate of frag grenades.%nDamage: %dmg%%nUses left: %uses%</desc>
		<init>
		setUses(10);
		var dmg = 25;
		var unpack = function() {
			user.addItem("Grenade", uses);
			used();
		}
	 	</init>
		<use>
		if(canUse()) {
			write('You throw a grenade!\nTargets:');
			if(targets.length > 0) {
				for(var i = 0; i &lt; targets.length; i++) {
					write(targets[i].getName() + '\n');
				}
				for(var i = 0; i &lt; targets.length; i++) {
					write(targets[i].getName() + ' takes ' + dmg + ' damage!\n');
					targets[i].damage(dmg);
				}
				used();
			} else {
				write('No targets!\n');
			}
		}
		</use>
	</item>
	<item refID="04-RBLD" scriptLang="JavaScript">
		<name>Rusting Blade</name>
		<desc>An old blade, coated with blood and rust. Holding it fills you with confidence.%nDoes %dmg% damage.</desc>
		<init>
		addStatAura('Strength',5);
		addStatAura('Intelligence',-3);
		setUses(15);
		var dmg = 15;
		var userDmg = 2;
		</init>
		<use>
		if(canUse()) {
			write('You charge forward!');
			if(targets.length > 0) {
				for(var i = 0; i &lt; targets.length; i++) {
					targets[i].damage(dmg);
				}
			} else {
				write('But had no direction, and hit a wall.\nTook ' + userDmg + ' damage!');
				user.damage(userDmg);
			}
			used();
		}
		</use>
	</item>
	<item refID="05-HSYS" scriptLang="JavaScript">
		<name>HUD System</name>
		<desc>A small round object that reads in big green letters:%n%t&quot;ARCTAN HUD SYSTEM(tm)&quot;%nIt is %state%.</desc>
		<init>
		var state = 'ON';
		setUses(0);
<!-- 		var affect = function(creature) { -->
<!-- 			if(creature instanceof Packages.sineSection.spaceRPG.character.Player) { -->
<!-- 				Java.to(creature, Packages.sineSection.spaceRPG.character.Player); -->
<!-- 				creature.setHasHud(true); -->
<!-- 			} -->
<!-- 		}; -->
<!-- 		var unaffect = function(creature) { -->
<!-- 			if(creature instanceof Packages.sineSection.spaceRPG.character.Player) { -->
<!-- 				Java.to(creature, Packages.sineSection.spaceRPG.character.Player); -->
<!-- 				creature.setHasHud(false); -->
<!-- 			} -->
<!-- 		}; -->
<!-- 		addAbilityAura('Allows user to view their stats.', affect, unaffect); -->
		var HudAura = Java.type('sineSection.spaceRPG.world.item.aura.HudAura');
		addAura(new HudAura());
		</init>
		<use>
		if(user instanceof Java.type('sineSection.spaceRPG.character.Player')) {
			user.setHasHud(!user.hasHud());
			if(user.hasHud())
				state = 'ON';
			else
			 	state = 'OFF';
		}
		</use>
	</item>
</define>